language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  postgresql: "9.6"
  apt:
    sources:
      - pov-wkhtmltopdf
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - wkhtmltopdf  # only add if needed and check the before_install section below

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
 - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
 - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
 - travis_install_nightly
 - pip install PyPDF2==1.18

script:
    - travis_run_tests

after_success:
  - travis_after_tests_success

branches:
  except:
    - /^merge-branch-.*$/
